### ISSUE TITLE
Layout broken , no way to open windows

### ISSUE THREAD

**Issue by titonix** [WolvenKit/WolvenKit#1641] opened 2024-04-15 00:59 UTC
**Describe the bug**
Every version of WKit I install has an empty layout upon making or opening a project, you have to use the reset layout button to get the default layout, but this doesnt allow you to open other windows I need.

**To Reproduce**
1. Download any version of Wkit (Nightly, portable, stable, etc)
2. Open or make a project
3. The window is blank
4. See logs

**Version**
 - Any version

**Screenshots**
![image](https://github.com/WolvenKit/WolvenKit/assets/70404195/81e71946-96c7-41fd-8067-356433964ff4)

Heres my log
[message.txt](https://github.com/WolvenKit/WolvenKit/files/14972836/message.txt)

Ive deleted layout.xml , Dockstates, reinstalled, deleted cache in appdata, windows system scan, I dont know what else to do.

**Comment by manavortex** [comment] 2024-04-19 08:57
Your log says that Wolvenkit tries to load the (default) layout from `C:\Users\user\AppData\Roaming\REDModding\WolvenKit\DockStates.xml` - if you deleted that file, then it should restore the bundled default. 
I think it's more likely that there's a missing dependency. Check the [troubleshooting guide](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/user-guide-troubleshooting) and install everything from the red box at the top, does that fix it?

**Comment by titonix** [comment] 2024-04-20 07:39
> Your log says that Wolvenkit tries to load the (default) layout from `C:\Users\user\AppData\Roaming\REDModding\WolvenKit\DockStates.xml` - if you deleted that file, then it should restore the bundled default. I think it's more likely that there's a missing dependency. Check the [troubleshooting guide](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/user-guide-troubleshooting) and install everything from the red box at the top, does that fix it?

I have all the dependencies installed, I followed all the steps in the red and yellow box to the same error.

**Comment by manavortex** [comment] 2024-04-20 09:20
Are you using the installer or the portable version?

**Comment by titonix** [comment] 2024-04-20 18:00
> Are you using the installer or the portable version?

Ive tried both as well as older versions

**Comment by manavortex** [comment] 2024-04-20 18:04
Can you try
- creating a new Windows user account (can be temporary)
- extract the portable Wolvenkit version directly from the archive somewhere on your harddrive's root folder (`C:\Wolvenkit` or something)
- Running it (without administrator privileges)
... and see if that fixes it? That'll give us another data point at least

**Comment by titonix** [comment] 2024-04-20 18:24
> Can you try
> 
> * creating a new Windows user account (can be temporary)
> * extract the portable Wolvenkit version directly from the archive somewhere on your harddrive's root folder (`C:\Wolvenkit` or something)
> * Running it (without administrator privileges)
>   ... and see if that fixes it? That'll give us another data point at least

Same issue, I believe its an issue with my .net install so ill try reinstalling the dependencies

**Comment by manavortex** [comment] 2024-04-20 18:25
It's the only thing I can think of at this point. If it doesn't work out-of-the-box, make sure to install both the x64 and the x86 versions, just to be sure...

**Comment by manavortex** [comment] 2024-07-13 16:34
Closing this since it has been quiet here. 

# Potential fixes (try them one by one)

### Check the dependencies
- The [troubleshooting guide](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/user-guide-troubleshooting) has a red box at the top, listing all dependencies you could possibly need. Install everything, both x64 and x86.

### Open Wolvenkit standalone
If you've opened Wolvenkit by double-clicking a `.cpmodproj`, try opening WKit from the start menu and loading the project via menu.

### Delete config files
Always delete all of these files. If step 1 doesn't work, do step 1 and 2, if step 2 doesn't work, do step 1, 2 and 3.
1. In your project folder, delete the `layout.xml`. This will force Wolvenkit to restore the settings from the user directory.
2. Inside `%APPDATA%\RedModding\Wolvenkit`, delete `DockStates.xml`
3. In your project folder, delete `fileTreeState.json`
4.  Inside `%APPDATA%\RedModding\Wolvenkit`, delete `config.json`

### Ask someone else to open your project
If they can't open it either, the problem is your project. In that case, open another issue with the entire folder as a zip.
If they can open it and you can't, the problem is your PC. You can try creating another Windows User and see if that one can run the project, or try running WKit as administrator/not as administrator and see if that helps.

**Closed by manavortex** 2024-07-13 16:34 UTC
Labels: bug
