### ISSUE TITLE
LocKeys

### ISSUE THREAD

**Issue by TeraLogin** [WolvenKit/WolvenKit#1207] opened 2023-03-10 19:18 UTC
TweakDB Browser can't show a single LocKey. When I click on a string with a LocKey on it, the string becomes empty.
LockKey Browser shows two columns. When I type a number in there, nothing happens too.
I don't understand what is wrong. I have the latest .Net framework runtime installed. I believe this have started when Cyberpunk got an update.

**Comment by seberoth** [comment] 2023-03-11 09:04
> TweakDB Browser can't show a single LocKey

Cant reproduce this. Here is mine:
![grafik](https://user-images.githubusercontent.com/456881/224475467-af7c52fe-ac7e-4d75-a63b-c92c469aa3c5.png)

Maybe add more info?

> LockKey Browser shows two columns. When I type a number in there, nothing happens too.

This should be fixed soon

**Comment by TeraLogin** [comment] 2023-03-11 10:05
Also I get these errors when I try to install a plugin for WolvenKit. It shows a path D:/a/WolvenKit. But I don't hive it on my drive. The actual path is D:/Modding/WolvenKit

[11.03.2023 17:00:53] Failed to extract plugin zip: C:\Users\teral\AppData\Local\Temp\TweakXL-1.1.2.zip
[11.03.2023 17:00:53] Message: The calling thread cannot access this object because a different thread owns it.
Source: WindowsBase
StackTrace:    at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.MenuItem.SetBoolField(UIElement element, BoolField field, Boolean value)
   at System.Windows.Controls.MenuItem.UpdateCanExecute()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.NotifyCanExecuteChanged()
   at WolvenKit.App.ViewModels.Shell.AppViewModel.set_TaskStatus(EStatus value) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\WolvenKit.App.ViewModels.Shell.AppViewModel.g.cs:line 23
   at WolvenKit.App.ViewModels.Shell.AppViewModel.ProgressService_PropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\AppViewModel.cs:line 125
   at System.ProgressService`1.NotifyPropertyChanged(String propertyName) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 68
   at System.ProgressService`1.set_Status(EStatus value) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 146
   at System.ProgressService`1.OnReport(T value) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 83
   at System.ProgressService`1.System.IProgress<T>.Report(T value) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 94
   at WolvenKit.App.Services.PluginService.ExtractZip(String zipPath, String extractPath) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\PluginService.cs:line 430
[11.03.2023 17:00:53] Unhandled exception in WolvenKit v8.8.2.0
[11.03.2023 17:00:53] Message: The calling thread cannot access this object because a different thread owns it.
Source: WindowsBase
StackTrace:    at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.MenuItem.SetBoolField(UIElement element, BoolField field, Boolean value)
   at System.Windows.Controls.MenuItem.UpdateCanExecute()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.NotifyCanExecuteChanged()
   at WolvenKit.App.ViewModels.Shell.AppViewModel.set_TaskStatus(EStatus value) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\WolvenKit.App.ViewModels.Shell.AppViewModel.g.cs:line 23
   at WolvenKit.App.ViewModels.Shell.AppViewModel.ProgressService_PropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\AppViewModel.cs:line 125
   at System.ProgressService`1.NotifyPropertyChanged(String propertyName) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 68
   at System.ProgressService`1.set_Status(EStatus value) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 146
   at System.ProgressService`1.OnReport(T value) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 83
   at System.ProgressService`1.Completed() in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\ProgressService.cs:line 113
   at WolvenKit.App.Services.PluginService.ExtractZip(String zipPath, String extractPath) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\PluginService.cs:line 474
   at WolvenKit.App.Services.PluginService.<>c__DisplayClass13_0.<InstallPluginAsync>b__2() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\PluginService.cs:line 339
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WolvenKit.App.Services.PluginService.InstallPluginAsync(EPlugin id) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\PluginService.cs:line 339
   at WolvenKit.App.ViewModels.HomePage.Pages.PluginViewModel.Install() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\HomePage\Pages\PluginViewModel.cs:line 136
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by seberoth** [comment] 2023-03-11 10:07
Please don't post all your bugs into one ticket...

**Comment by TeraLogin** [comment] 2023-03-11 10:24
I have found have how to replicate the issue. The LocKeys are shown when Windows 11 UI scale is set to 100%. But when I set UI scale to 125% they are not working.

**Comment by TeraLogin** [comment] 2023-03-11 10:42
The LocKeys are shown only if a project was opened. If I launch WolvenKit and click on "Continue to editor ->", they don't.

**Comment by seberoth** [comment] 2023-03-11 10:45
Loading archive files is currently only supported when a project is loaded and since the LocKeys are in the archives...

**Closed** 2023-03-11 10:48 UTC
Labels: bug
