### ISSUE TITLE
Some of Female V's voice lines loop and fade out until inaudible when exported

### ISSUE THREAD

**Issue by AnythingVocaloid** [WolvenKit/WolvenKit#1585] opened 2024-03-02 15:26 UTC
**Describe the bug**
I tried extracting V's voice lines from the game to see what's new in 2.0, and I found that, when extracted, some of the lines repeat themselves, while fading out until nothing can be heard, and then they stop.

**To Reproduce**
1. Navigate to base/ep1 > localization > en-us > vo
2. Filter names by "Begins With: v_" and "Contains: _f_"
3. Use Ctrl + A to select all files
4. Right click > Add to Project
5. Once all files are exported, use foobar2000 with the vgmstream plugin to open a .wem file and you'll find that some lines repeat themselves (example waveform rendered in Audacity attached)

**Expected behavior**
Voice lines do not loop and instead play out as heard in the game.

**Version (please complete the following information):**
 - Version 8.12.2

**Screenshots**
![loop](https://github.com/WolvenKit/WolvenKit/assets/49313670/b88dc166-e1d6-426e-bd2a-c83fb95b09e9)

**Comment by seberoth** [comment] 2024-03-02 17:05
Duplicate of #1396

**Closed by seberoth** 2024-03-02 17:05 UTC
Labels: bug
