### ISSUE TITLE
MCF_RenderInScene gets added to shadow mesh upon import

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1418] opened 2023-11-05 19:23 UTC
When importing a glb into a shadow mesh, the resulting mesh will have the MCF_RenderInScene render mask, even if the mesh didn't previously have it.

![wolvenkit_bug_shadow_mesh](https://github.com/WolvenKit/WolvenKit/assets/965785/00abfe5f-26da-4775-b55c-91da362e166d)

The property is set in [`MeshImportTools.cs:1068`](https://github.com/WolvenKit/WolvenKit/blob/6f11964a2609bf73b06e0d13201d7c1023aedcb6/WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs#L1068). IMO, the only thing necessary here would be to check if it's set in the file that we're writing into, but I don't know how to do that.

**Comment by seberoth** [comment] 2023-11-05 21:48
Not a bug. Was a design desicion made by @HitmanHimself. Don't know why, maybe he can tell more

**Comment by manavortex** [comment] 2024-02-09 11:39
<img width="579" alt="image" src="https://github.com/WolvenKit/WolvenKit/assets/965785/65cbc401-e646-44f6-af65-4e71c17c5a95">
Hitman agrees with preserving the flags from the source mesh :)

**Comment by seberoth** [comment] 2024-03-09 22:21
Fixed with 5a9d05a

**Closed by seberoth** 2024-03-09 22:21 UTC
Labels: bug, mesh
