### ISSUE TITLE
"Copy relative path" crashes WolvenKit

### ISSUE THREAD

**Issue by njibhu** [WolvenKit/WolvenKit#795] opened 2022-05-23 22:46 UTC
**Describe the bug**
WolvenKit crashes when trying to copy the filepath of any item in the archive/

**To Reproduce**
1. Select a file in the "Asset browser" panel
2. On the "File Information" panel, right click on the FullName row
3. Click on the menu item "Copy relative path"
4. App crashes

**Stacktrace**
```
2022-05-24 00:39:03.561 [ERR] Unhandled exception in WolvenKit v8.6.0.0
2022-05-24 00:39:03.613 [ERR] Message: Object reference not set to an instance of an object.
Source: WolvenKit
StackTrace:    at WolvenKit.Views.Tools.PropertiesView.CopyMenuItem_Click(Object sender, RoutedEventArgs e) in D:\a\WolvenKit\WolvenKit\WolvenKit\Views\Tools\PropertiesView.xaml.cs:line 623
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WolvenKit Nightly 8.6.0
 - Cyberpunk 1.52

**Comment by ja-to** [comment] 2022-05-27 00:08
I was unable to reproduce the crash using the 8.6.0 release. Can you check if the issue is fixed on your machine using the release version and report back? Thanks!

Additionally if you're not already aware, files within the Asset Browser can be right-clicked directly which brings up a context menu containing the "Copy relative path" function as well.

**Comment by njibhu** [comment] 2022-05-29 15:24
Just tried using this version: https://github.com/WolvenKit/WolvenKit/releases/tag/8.6
Still crashes on my side. Here a screenshot to make sure we're talking about the same thing:
![crash](https://user-images.githubusercontent.com/4581742/170877279-eef433de-b639-4319-a424-6e4b2027b782.png)

**Comment by njibhu** [comment] 2022-05-29 15:27
Additionally: The workaround of right/clicking directly on the Asset Browser works and does not crash WolventKit. I'll use this for now ! Thanks for the trick

**Closed** 2022-07-08 20:02 UTC
Labels: bug
