### ISSUE TITLE
Trying to add certain records from the tweak browser results in an error message

### ISSUE THREAD

**Issue by FacelessV1** [WolvenKit/WolvenKit#1838] opened 2024-07-10 03:34 UTC
**Describe the bug**
When i try to add "Vehicle.v_standard2_archer_quartz_nomad_player" and "Vehicle.v_standard2_archer_quartz_nomad_player_02"
i  get this error message: 
[2024-07-10 05:29:13] [Error    ] Failed to create TweakXL yaml. Error: System.ArgumentNullException: Exception of type 'System.ArgumentNullException' was thrown. (Parameter 'raRef.DepotPath.ToString()')
   at WolvenKit.Core.Extensions.Ensure.NotNull[T](T obj, String message, String parameterName) in D:\a\WolvenKit\WolvenKit\WolvenKit.Core\Extensions\Ensure.cs:line 51
   at WolvenKit.App.Models.TweakXLYamlTypeConverter.WriteREDRaRef(IEmitter emitter, IRedResourceAsyncReference raRef, String property) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Models\TweakXL.cs:line 282
   at WolvenKit.App.Models.TweakXLYamlTypeConverter.WriteYaml(IEmitter emitter, Object value, Type type) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Models\TweakXL.cs:line 438
   at YamlDotNet.Serialization.ObjectGraphVisitors.CustomSerializationObjectGraphVisitor.Enter(IObjectDescriptor value, IEmitter context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](Object name, IObjectDescriptor value, IObjectGraphVisitor`1 visitor, TContext context, Stack`1 path)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.YamlDotNet.Serialization.IObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor graph, IObjectGraphVisitor`1 visitor, TContext context)
   at YamlDotNet.Serialization.SerializerBuilder.ValueSerializer.SerializeValue(IEmitter emitter, Object value, Type type)
   at YamlDotNet.Serialization.Serializer.EmitDocument(IEmitter emitter, Object graph, Type type)
   at YamlDotNet.Serialization.Serializer.Serialize(IEmitter emitter, Object graph)
   at YamlDotNet.Serialization.Serializer.Serialize(TextWriter writer, Object graph)
   at YamlDotNet.Serialization.Serializer.Serialize(Object graph)
   at WolvenKit.App.ViewModels.Tools.TweakBrowserViewModel.ExecuteConvertToYAML() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\TweakBrowserViewModel.cs:line 362

**Loomy suspected its due to missing .inkstyle file, for all vehicles in that category, bad raref hash/path for widgetStyleSheetPath**

To reproduce this bug open the tweak browser and attempt to add either Vehicle.v_standard2_archer_quartz_nomad_player" or "Vehicle.v_standard2_archer_quartz_nomad_player_02" to the project. This always results in the error message provided above.

 - Version: Whatever the latest version is as of July 10th 2024

**Comment by kmirea** [comment] 2024-07-10 20:36
The inkstyle is missing for this, or the format is depreciated ? All vehicles in this group have bad widgetstyle links (.inkstyle)

There are other ink related files through for Archer, in same folder, and other vehicles or variant or archer still have inkatlas, could those be duplicated, or raref set to another inkstyle ?
`base\gameplay\gui\widgets\vehicle\archer`

**Comment by manavortex** [comment] 2024-07-13 09:47
Duplicate of #1842

**Closed** 2024-07-13 09:47 UTC
Labels: bug
