### ISSUE TITLE
WolvenKit 8.12.2 stays in the background even after I exit

### ISSUE THREAD

**Issue by Dufresne240** [WolvenKit/WolvenKit#1569] opened 2024-02-16 09:32 UTC
When I click the exit button, I thought that would end WolvenKit in the background but after checking task manager it's still there taking up about 2gb memory.

 - Version 8.12.2 (stable)

**Comment by rfuzzo** [comment] 2024-02-16 09:49
I cannot reproduce this. 

Can you tell me the steps you need to take (open some tool or so?) in Wolvenkit so that this happens?

**Comment by seberoth** [comment] 2024-02-17 13:48
Steps to reproduce:
1. Open any mesh file
2. Switch to preview tab
3. Close mesh file while preview is open
4. Close WolvenKit

Switching tab back to CR2W view before closing the file and WKit stops properly. 
Some Helix thread is blocking the shutdown.

Probably the same for #1508

**Comment by CyanideX** [comment] 2024-11-24 03:23
I am still seeing this issue with 8.15+. I don't have steps to reproduce but I often leave my instances open while putting my PC to sleep, open multiple instances of WK, and switch between various projects. I will notice WK slowing down significantly and then, when opening task manager, I am greeted with multiple instances stuck in the background.

![image](https://github.com/user-attachments/assets/37a4f0f5-de59-4392-a816-b0b5440b72bf)

**Comment by notaspirit** [comment] 2024-11-24 08:10
I've seen this happen too a couple of times even on the latest nightlies. Seems to have started around the time I popping out windows regularly. Don't remember it happening before that.

**Comment by seberoth** [comment] 2024-11-24 08:24
> I've seen this happen too a couple of times even on the latest nightlies. Seems to have started around the time I started popping out windows regularly. Don't remember it happening before that.

Good hint.
Seems to happen when you close WKit while a 3D Viewer (Mesh preview, Sector preview, ... ) is open in a floating (popup) window

Is it the same for you @CyanideX ?

**Comment by notaspirit** [comment] 2024-11-24 09:05
I wasn't using any 3d view floating window when I observed it, just import / export on a diff monitor, but a 3d preview might've been open on the main window.

**Comment by manavortex** [comment] 2024-11-24 11:52
It might well be _any_ undocked window. It happens to me as well, but I haven't tried or bothered to reproduce it yet (instead just wrote a bat script...)

**Comment by CyanideX** [comment] 2024-11-24 16:53
I am pretty certain I have had it happen without any undocked windows; I rarely move them.

**Comment by notaspirit** [comment] 2024-12-01 19:57
I am able to recreate the issue 100% of the time on version 8.15.1-2024-11-25
1. open any wolvenkit project (floating windows don't matter)
2. first open a mesh file then an xbm file, the order matters however it doesn't matter if it's from the project or the archives
3. close wolvenkit while the files are open
4. observe in task manager as all wolvenkit processes disappear except one which drops to 0% cpu usage after max 10-15s and stays there taking up ram
if 2 mesh files or 2 xbm files are open the process closes fully as expected, haven't tested other file type combinations.

**Comment by seberoth** [comment] 2024-12-02 05:55
@notaspirit 

Almost.
Happens if the "File Properties" is shown and a mesh was shown there (the preview) but switch to something else after.
Can you confirm?

**Comment by seberoth** [comment] 2024-12-02 05:57
But to boil it down, it is the Mesh Preview again, which doesn't properly close.

**Closed** 2024-12-17 11:55 UTC
Labels: bug
