### ISSUE TITLE
.app file: WKit doesn't set scale (and lies about it)

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1191] opened 2023-03-04 15:43 UTC
Wolvenkit Nightly 03-03:

When setting the scale of a component in an .app file, Wolvenkit doesn't write the changes back to disk (and lies about it). Display will reset when I re-open the file.
https://user-images.githubusercontent.com/965785/222915361-fc85aa93-b218-4d61-9b57-9a49b1ea7409.mp4

It doesn't always happen - maybe only for Z, and maybe only for scaling it back? Anyhow, I've attached my .app file

[cherry_tree_app.zip](https://github.com/WolvenKit/WolvenKit/files/10889044/cherry_tree_app.zip)

**Comment by seberoth** [comment] 2023-03-04 17:06
Duplicate of #1166
Before you posted the next one: Yes, it applies to Vec2 too

Workaround: Don't use it. Open it open and edit the individual values

**Closed by seberoth** 2023-03-04 17:06 UTC
Labels: bug

**Comment by manavortex** [comment] 2023-03-04 17:07
Behaved different, so I didn't even consider that :) Thank you for addressing this! <3
