### ISSUE TITLE
Quest Graph Editor

### ISSUE THREAD

**Issue by extract** [WolvenKit/WolvenKit#575] opened 2021-08-29 19:32 UTC
Add quest graph viewer/editor. I think it was part of W3 WolvenKit but I have not used it.

I find it a bit tricky to edit quests with the lack of proper editor. Currently, only chunks are printed.

Thank you

**Comment by rfuzzo** [comment] 2021-08-29 19:32
yes.

**Comment by rfuzzo** [comment] 2021-08-29 19:35
In all seriousness: we don't have an issue tracking this. So this is good.

**Comment by Traderain** [comment] 2021-08-30 09:00
Actually #4

**Comment by HitmanHimself** [comment] 2021-09-02 09:57
we need a general purpose graph editor anyways, there are more file formats that could take advantage of such an editor

**Comment by extract** [comment] 2021-09-07 16:56
Yeah, actually the more I looked into the structure I see that a lot of files have that type of node/graph structure. Just a beginners misunderstanding on my part.

**Comment by rfuzzo** [comment] 2023-08-22 07:03
closing as duplicate of #4

**Closed by rfuzzo** 2023-08-22 07:03 UTC
Labels: help wanted, epic
