### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#367] opened 2021-02-17 12:58 UTC
Create an installer with wix for the project (https://wixtoolset.org/):
- Download .net if needed
- Install the program
- Associate files with wkit icon

**Comment by Offline-R503B** [comment] 2021-02-17 14:29
WebView2 Distribution should happen here too.

**Comment by rfuzzo** [comment] 2021-02-17 14:31
We also need to implement file opening with Wolvenkit for (3)

**Comment by Moonded** [comment] 2021-03-01 22:45
Installer is being handled by Zathedeadgamer using installforge

**Comment by N00bWizard** [comment] 2021-03-17 23:09
Installer is made and functions as intended. Will keep updating tho.

**Comment by N00bWizard** [comment] 2021-04-05 19:01
Installer works as intended and is ready for deployment. Fixes & addtions will be added with time. 
please close issue. Thanks.

**Comment by Offline-R503B** [comment] 2021-04-06 13:16
Closing issue : Installer functions well.

A future idea could be to swap to installshield.

Other than that we all guud

**Closed by Offline-R503B** 2021-04-06 13:16 UTC
Labels: prio-b
